# Generated by Django 5.2 on 2025-10-20 16:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('word_count', models.IntegerField(default=0, verbose_name='单词数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='阅读时间')),
                ('read_duration', models.IntegerField(default=0, verbose_name='阅读时长(秒)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '阅读历史',
                'verbose_name_plural': '阅读历史',
                'db_table': 'reading_history',
                'ordering': ['-read_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('word', models.CharField(max_length=100, verbose_name='单词')),
                ('color', models.CharField(max_length=20, verbose_name='标注颜色')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注',
                'db_table': 'annotations',
                'unique_together': {('article', 'user_ip', 'word')},
            },
        ),
    ]
