# Generated by Django 5.2 on 2025-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraph_count',
            field=models.IntegerField(default=0, verbose_name='段落数'),
        ),
    ]
