# Generated by Django 5.2 on 2025-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_paragraph_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='paragraphs',
            field=models.JSONField(blank=True, default=list, verbose_name='段落数据'),
        ),
    ]
