# Generated by Django 5.2 on 2025-10-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_paragraphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='username',
            field=models.CharField(default='guest', max_length=50, verbose_name='用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('article', 'username')},
        ),
    ]
