# Generated by Django 5.2 on 2025-10-24 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_recommended_readinghistory_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='guest', max_length=50, verbose_name='用户名')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'favorites',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'username')},
            },
        ),
    ]
