# Generated by Django 5.2 on 2025-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='admin', max_length=50, verbose_name='作者'),
        ),
    ]
