# Generated by Django 5.2 on 2025-10-25 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('word_count', models.IntegerField(default=0, verbose_name='单词数')),
                ('paragraph_count', models.IntegerField(default=0, verbose_name='段落数')),
                ('paragraphs', models.JSONField(blank=True, default=list, verbose_name='段落数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('author', models.CharField(default='admin', max_length=50, verbose_name='作者')),
            ],
            options={
                'verbose_name': '语法文章',
                'verbose_name_plural': '语法文章',
                'db_table': 'grammar_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGrammarArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('difficulty', models.CharField(choices=[('beginner', '初级'), ('intermediate', '中级'), ('advanced', '高级')], default='intermediate', max_length=20, verbose_name='难度')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='分类')),
                ('word_count', models.IntegerField(default=0, verbose_name='单词数')),
                ('paragraph_count', models.IntegerField(default=0, verbose_name='段落数')),
                ('paragraphs', models.JSONField(blank=True, default=list, verbose_name='段落数据')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('author', models.CharField(default='guest', max_length=50, verbose_name='作者')),
            ],
            options={
                'verbose_name': '用户语法文章',
                'verbose_name_plural': '用户语法文章',
                'db_table': 'user_grammar_articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
