# Generated by Django 5.2 on 2025-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_grammararticle_usergrammararticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_format',
            field=models.CharField(choices=[('plain', '纯文本'), ('markdown', 'Markdown'), ('html', 'HTML')], default='plain', max_length=20, verbose_name='内容格式'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='是否为Markdown格式'),
        ),
        migrations.AddField(
            model_name='grammararticle',
            name='content_format',
            field=models.CharField(choices=[('plain', '纯文本'), ('markdown', 'Markdown'), ('html', 'HTML')], default='plain', max_length=20, verbose_name='内容格式'),
        ),
        migrations.AddField(
            model_name='grammararticle',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='是否为Markdown格式'),
        ),
        migrations.AddField(
            model_name='usergrammararticle',
            name='content_format',
            field=models.CharField(choices=[('plain', '纯文本'), ('markdown', 'Markdown'), ('html', 'HTML')], default='plain', max_length=20, verbose_name='内容格式'),
        ),
        migrations.AddField(
            model_name='usergrammararticle',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='是否为Markdown格式'),
        ),
    ]
